<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Jose-JWT" Version="5.1.1" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.8.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="NSec.Cryptography" Version="24.4.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.8.0" />
    <ProjectReference Include="../Credentials/Credentials.csproj" />
  </ItemGroup>

</Project>
